# Generated by Django 4.2.4 on 2023-08-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEFAULT_DAYS', models.IntegerField(blank=True, verbose_name='画像描画時の取得日数')),
                ('DEFAULT_LONG_MACD', models.IntegerField(blank=True, verbose_name='macd取得の長期スパン')),
                ('DEFAULT_MIDDLE_MACD', models.IntegerField(blank=True, verbose_name='macd取得の中期スパン')),
                ('DEFAULT_SHORT_MACD', models.IntegerField(blank=True, verbose_name='macd取得の短期スパン')),
            ],
        ),
    ]
